# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kotlin Recipes
#email: im@msingh.me
logo: /kotlinrecipes.github.io/assets/images/logo_icon.png
description: > 
  Kotlin Recipes is built to introduce new laravel developers as well as 
  Experenced developers to the hidden (secret) features of Kotlin. It 
  uncovers deepest hidden features that can be extremely helpful. 
  #baseurl: "kotlinrecipes.github.io" 
baseurl: ""
copyright: | 
  Copyright &copy; 2017 <a href="https://kotlinrecipes.com/" target="_blank">Kotlin Recipes</a>. All rights reserved.
url: https://www.kotlinrecipes.com
twitter_username: kotlinrecipes
github_username:  kotlinrecipes

permalink: /:categories/:title

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

author:
  name: Danny Preussler
  picture: /assets/images/2426606.png

